[project]
name = "zenpulse"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.meditation-tracker]
path = "contracts/meditation-tracker.clar"
depends_on = []

[contracts.user-profile]
path = "contracts/user-profile.clar"
depends_on = []

[contracts.zen-token]
path = "contracts/zen-token.clar"
depends_on = []

[contracts.zenpulse-profile]
path = "contracts/zenpulse-profile.clar"
depends_on = []

[contracts.zenpulse-sessions]
path = "contracts/zenpulse-sessions.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
